#!/usr/bin/env python3
"""Build a clean, upload-ready copy of this project - and open it.

Solves the "Yowza, that's a big file (25MB)" problem for good: your working folder contains
ipo_desk.db (tens of MB, and it grows), which must never go to GitHub. This script copies only
the files GitHub needs into a fresh folder next to your project, checks the sizes, and shows
you the result.

    python make_upload_folder.py            # -> ..\\ipo-desk-upload\\ipo-desk
    python make_upload_folder.py --dest D:\\Upload
"""
import argparse
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# everything the repository needs - nothing else
FILES = [
    "dashboard.html", "ipo_desk.py", "sources.py", "merge.py", "store.py", "value.py", "util.py",
    "market.py",                                      # the GMP / grey-market feed (imported by ipo_desk.py)
    "cg_sub_cache.json", "cg_sub_backfill.py",        # the archive of category-wise bidding records
    "ohlc_backfill.py",                               # the daily-candles backfill for the price study
    "export_static.py", "serve_site.py", "seed_export.py", "check_upload.py",
    "day1.py", "xlsx.py", "build_standalone.py",
    "requirements.txt", "start.bat", "start.sh", "publish-now.bat", "check-upload.bat",
    "make_upload_folder.py", "make-upload-folder.bat",
    "README.md", "SETUP-ONLINE.md", "workflow.yml", ".gitignore",
]
HIDDEN = [os.path.join(".github", "workflows", "ipo-desk.yml")]
OPTIONAL_DIRS = ["seed"]          # generated by seed_export.py - include if it exists

# things that must never be copied, listed so we can shout if one sneaks in
BANNED_SUFFIX = (".db", ".db-wal", ".db-shm", ".pyc", ".json.gz.tmp")


def _local_imports():
    """Every module this project imports from its own folder - scanned, not guessed."""
    import ast
    here = {f[:-3] for f in os.listdir(HERE) if f.endswith(".py")}
    need = set()
    for stem in here:
        try:
            tree = ast.parse(open(os.path.join(HERE, stem + ".py"), encoding="utf-8").read())
        except (OSError, SyntaxError):
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                need.update(a.name.split(".")[0] for a in node.names)
            elif isinstance(node, ast.ImportFrom) and node.module:
                need.add(node.module.split(".")[0])
    return need & here


def build(dest_root):
    target = os.path.join(dest_root, "ipo-desk")
    # safety net: if a shipped file imports a module that is not in FILES, add it now
    listed = {f[:-3] for f in FILES if f.endswith(".py")}
    extra = sorted(m for m in _local_imports() if m + ".py" not in FILES and m not in listed)
    if extra:
        print("  (auto-added modules that the list had missed: " + ", ".join(x + ".py" for x in extra) + ")")
        FILES.extend(x + ".py" for x in extra)
    if os.path.exists(target):
        shutil.rmtree(target)
    os.makedirs(target)

    copied, missing, total = [], [], 0
    for rel in FILES + HIDDEN:
        src = os.path.join(HERE, rel)
        if not os.path.exists(src):
            if rel in HIDDEN or rel == "workflow.yml":
                alt = os.path.join(HERE, "workflow.yml")
                if rel == ".github/workflows/ipo-desk.yml" and os.path.exists(alt):
                    dst = os.path.join(target, rel)
                    os.makedirs(os.path.dirname(dst), exist_ok=True)
                    shutil.copyfile(alt, dst)
                    copied.append(rel)
                    total += os.path.getsize(dst)
                    continue
            missing.append(rel)
            continue
        dst = os.path.join(target, rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(src, dst)
        copied.append(rel)
        total += os.path.getsize(dst)

    for d in OPTIONAL_DIRS:
        src = os.path.join(HERE, d)
        if not os.path.isdir(src):
            continue
        os.makedirs(os.path.join(target, d), exist_ok=True)
        for f in os.listdir(src):
            if f.endswith(".gz"):
                shutil.copyfile(os.path.join(src, f), os.path.join(target, d, f))
                copied.append(os.path.join(d, f))
                total += os.path.getsize(os.path.join(src, f))

    print(f"created {target}")
    print(f"  {len(copied)} files, {total/1024:.0f} KB in total")
    if missing:
        print(f"  ! not found in {HERE}: {', '.join(missing)}")

    # safety net: nothing forbidden may exist in the new folder
    bad = [os.path.join(dp, f) for dp, _, fs in os.walk(target) for f in fs
           if f.endswith(BANNED_SUFFIX) or f.startswith("ipo_desk.db")]
    if bad:
        print("  !! unexpected files removed:", bad)
        for b in bad:
            os.remove(b)

    # big-file guard (github.com web upload limit)
    over = [(os.path.getsize(os.path.join(dp, f)), os.path.join(dp, f))
            for dp, _, fs in os.walk(target) for f in fs
            if os.path.getsize(os.path.join(dp, f)) > 20 * 1024 * 1024]
    if over:
        print("  !! still too big to upload:", over)
        return target, 1
    print("\nVERDICT: safe to drag into github.com (or commit with GitHub Desktop).")
    return target, 0


def main():
    ap = argparse.ArgumentParser(description="Build a clean folder that is safe to upload to GitHub")
    ap.add_argument("--dest", default=os.path.dirname(HERE),
                    help="where to create the ipo-desk-upload folder (default: the parent folder)")
    args = ap.parse_args()
    dest_root = os.path.join(args.dest, "ipo-desk-upload")
    os.makedirs(dest_root, exist_ok=True)
    target, code = build(dest_root)

    print("\nnext:  https://github.com/new  ->  name it ipo-desk, make it Public, Create repository")
    print("       then open this folder, Ctrl+A, drag everything into the browser, Commit changes:")
    print(f"       {target}")
    print("       (turn on View > Hidden items so .github is included)")
    if sys.platform.startswith("win"):
        try:
            subprocess.Popen(["explorer", os.path.normpath(target)])
            print("\n(opened the folder for you)")
        except Exception:
            pass
    return code


if __name__ == "__main__":
    sys.exit(main())
